/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ChemistryElements(props) {
  const { nodes, materials } = useGLTF("./uploads_files_3379235_Chemistry.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["500ml"].geometry}
        material={materials["Material.001"]}
        position={[-0.095, 0.434, 0.805]}
        rotation={[0, 1.188, 0]}
        scale={-0.183}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["500ml_liquid"].geometry}
        material={materials[" 0 Liquid "]}
        position={[-0.095, 0.418, 0.806]}
        rotation={[0, 1.188, 0]}
        scale={-0.181}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["250ml"].geometry}
        material={materials["Material.004"]}
        position={[-0.213, 0.252, 0.357]}
        rotation={[-Math.PI, -1.188, -Math.PI]}
        scale={-0.126}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["250ml_liquid"].geometry}
        material={materials[" 0 Liquid "]}
        position={[-0.213, 0.24, 0.356]}
        rotation={[-Math.PI, -1.188, -Math.PI]}
        scale={-0.125}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["125ml"].geometry}
        material={materials["Material.002"]}
        position={[-0.311, 0.24, -0.017]}
        rotation={[-Math.PI, -1.188, -Math.PI]}
        scale={-0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["125ml_liquid"].geometry}
        material={materials[" 0 Liquid "]}
        position={[-0.311, 0.234, -0.017]}
        rotation={[-Math.PI, -1.188, -Math.PI]}
        scale={-0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.Material}
        position={[-0.042, 0.418, -0.034]}
        rotation={[-Math.PI / 2, 0, -2.885]}
        scale={[0.096, -0.012, 0.214]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials.Glass}
        position={[-0.076, 0.569, -0.144]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials.Glass}
        position={[-0.108, 0.569, -0.269]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials.Glass}
        position={[-0.14, 0.569, -0.39]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials.Glass}
        position={[-0.172, 0.569, -0.514]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials.Glass}
        position={[-0.204, 0.569, -0.636]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials.Glass}
        position={[-0.237, 0.569, -0.76]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder021.geometry}
        material={materials["Red Liquid"]}
        position={[-0.076, 0.569, -0.144]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder022.geometry}
        material={materials["Pink Liquid"]}
        position={[-0.108, 0.569, -0.269]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder023.geometry}
        material={materials["Yellow Liquid"]}
        position={[-0.14, 0.569, -0.39]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder024.geometry}
        material={materials["Light Green"]}
        position={[-0.172, 0.569, -0.514]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder025.geometry}
        material={materials["Dark Green"]}
        position={[-0.204, 0.569, -0.636]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder026.geometry}
        material={materials[" Blue Liquid"]}
        position={[-0.237, 0.569, -0.76]}
        rotation={[0, -1.315, 0]}
        scale={0.033}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder018.geometry}
        material={materials.Glass}
        position={[0.496, 0.384, -0.041]}
        rotation={[0, -1.315, 0]}
        scale={0.151}
      />
      <group
        position={[0.496, 1.019, -0.041]}
        rotation={[0, -1.315, 0]}
        scale={0.019}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_1.geometry}
          material={materials.Material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_2.geometry}
          material={materials.Glass}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials["Light Green.001"]}
        position={[0.496, 0.301, -0.041]}
        rotation={[0, -1.315, 0]}
        scale={0.145}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder014.geometry}
        material={materials.Glass}
        position={[0.219, 0.301, -0.399]}
        rotation={[0, -1.315, 0]}
        scale={[0.019, 0.036, 0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder015.geometry}
        material={materials.Material}
        position={[0.219, 0.402, -0.399]}
        rotation={[0, -1.315, 0]}
        scale={[0.021, 0.008, 0.021]}
      />
      <group
        position={[-0.381, 0.221, -0.982]}
        rotation={[Math.PI, -0.901, Math.PI]}
        scale={[0.076, 0.01, 0.076]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder033_1.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder027.geometry}
        material={materials["Red Liquid.001"]}
        position={[-0.381, 0.221, -0.982]}
        rotation={[Math.PI, -0.901, Math.PI]}
        scale={[0.073, 0.01, 0.073]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.003"]}
        position={[0.07, 0.34, -0.853]}
        rotation={[0, -1.315, 0]}
        scale={[-0.146, -0.108, -0.146]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials.Water}
        position={[0.07, 0.34, -0.853]}
        rotation={[0, -1.315, 0]}
        scale={[-0.144, -0.107, -0.144]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Funnel.geometry}
        material={materials.Glass}
        position={[0.211, 0.303, -0.242]}
        rotation={[0, -1.315, -Math.PI]}
        scale={0.07}
      />
    </group>
  );
}

useGLTF.preload("./uploads_files_3379235_Chemistry.glb");
