/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFBX, useGLTF } from "@react-three/drei";

export function GlassDropper() {
  // const dropper = useFBX('./glass_dropper_2.0.gltf');
  const dropper = useGLTF('./glass_dropper_2.0.gltf');
  
  return <primitive
      object={dropper.scene}
      scale={1.5}
      position={[-0.1,5,1.7]}
      rotation-x={88*3.14159/180} 
      rotation-z={-88*3.14159/180}
      />;
}

// useGLTF.preload("./glassDropper.glb");
