/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function GlassDropper(props) {
  const { nodes, materials } = useGLTF("./glassDropper.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.dropper.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.rubber_head.geometry}
        material={materials["Material.003"]}
        position={[0, 0.901, 0]}
        scale={[1.1, 1.3, 1.1]}
      />
    </group>
  );
}

useGLTF.preload("./glassDropper.glb");
