/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Pipette(props) {
  const { nodes, materials } = useGLTF("./pipette.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pipet.geometry}
        material={materials.Material}
        position={[0, 0.24, 0]}
        scale={[0.83, 0.91, 0.83]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pipet1ml_wrap_1003.geometry}
          material={materials["pipet1ml wrap_1003"]}
          position={[0.07, 1.75, 0.02]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[3.65, 3.23, 2.95]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.01, 0.23, 0.1]}
        scale={13.33}
      />
    </group>
  );
}

useGLTF.preload("./pipette.glb");
