/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function TenMlCylinder(props) {
  const { nodes, materials } = useGLTF("./10ml_cylinder.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("./10ml_cylinder.glb");

