/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function VFlask10ML(props) {
  const { nodes, materials } = useGLTF("./vflask10ml.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.vflask10ml.geometry}
        material={materials["Material.002"]}
        scale={[1.042, 1.212, 1.042]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mark.geometry}
          material={materials.Material}
          position={[0, 2.919, 0]}
          scale={[0.38, 0.155, 0.38]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vflask10ml_wrap_1003.geometry}
          material={materials["vflask10ml wrap_1003"]}
          position={[0.953, 0.419, 0]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.723, 0.834, 0.717]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("./vflask10ml.glb");
